### ISSUE TITLE
Bookkeepers should handle NPT when generating equilibrium samples for periodic systems

### ISSUE THREAD

**Issue by jchodera** [choderalab/integrator-benchmark#10]
For systems like water boxes and Lennard-Jones fluids, we should be sure to allow the box size to fluctuate (and record the box vectors) when generating initial equilibrium samples. Currently, code like [this](https://github.com/choderalab/integrator-benchmark/blob/master/benchmark/testsystems/bookkeepers.py#L121) assumes the volume remains fixed.

We should be careful to remove or disable the barostat during work measurement trajectories, but it is important to have an appropriate equilibrium distribution sampled from NPT for these systems since the initial densities may have unphysical pressures if the volume is constrained.

Note that `WaterBox`, `DHFRExplicit`, and `SrcExplicit` should use 298K and 1atm, but the `LennardJonesFluid` should use a different set of parameters to keep it in the liquid or gas phases (depending on which one we want to simulate).

**Comment by maxentile** [comment]
Resolved in https://github.com/choderalab/integrator-benchmark/pull/32
