### ISSUE TITLE
Update openmmtools.testsystems with better defaults?

### ISSUE THREAD

**Issue by jchodera** [choderalab/integrator-benchmark#13]
`benchmark.testsystems` contains a bunch of settings that override the defaults to build useful testsystems with appropriate PME tolerances, etc. When appropriate, it would be useful to update the defaults in `openmmtools.testsystems` and create testsystem variants there that we can use directly, since this will make it easier to just use the "off the shelf" testsystems in other projects (e.g. the shadow work paper).

**Comment by maxentile** [comment]
Resolved by @jchodera  in https://github.com/choderalab/openmmtools/commit/686720250cd55d8e4af6870fb71a1f5568f19db6 by adding
```python
DEFAULT_EWALD_ERROR_TOLERANCE = 1.0e-5 # default Ewald error tolerance
DEFAULT_CUTOFF_DISTANCE = 10.0 * unit.angstroms # default cutoff distance
DEFAULT_SWITCH_WIDTH = 1.5 * unit.angstroms # default switch width
```
to openmmtools.testsystems
