### ISSUE TITLE
Travis failures

### ISSUE THREAD

**Issue by jchodera** [choderalab/integrator-benchmark#22]
@maxentile : It looks like [travis is failing for odd reasons](https://travis-ci.org/choderalab/integrator-benchmark/jobs/225193157#L499-L590
):
* The same `alanine_constrained` system generates samples multiple times
* Downstream processing can't find the `.npy` files generated

Is this primarily an issue of needing to provide a way to control where these data files are placed via an environment variable?

**Comment by maxentile** [comment]
Hmm, I think you're right -- looks like I did something incorrect with specifying filepaths (script looks for samples at `'benchmark/../data/alanine_constrained_samples.npy'`, doesn't find them, does sampling, saves newly-collected samples to `'benchmark/data/alanine_constrained_samples.npy'`...). Will address shortly...

(I don't encounter this error locally.)

**Comment by maxentile** [comment]
It was actually just because the `data` directory was in `.gitignore`. Fixed by ensuring the `data` and `figures` directories are created if they don't already exist...
