### ISSUE TITLE
Missing baoab_vs_aboba_analysis.py file

### ISSUE THREAD

**Issue by jchodera** [choderalab/integrator-benchmark#9]
[This line](https://github.com/choderalab/integrator-benchmark/blob/master/benchmark/experiments/baoab_vs_vvvr.py#L9) in the `master` branch refers to a `baoab_vs_aboba_analysis.py` file that doesn't seem to be in the repository.

I'm a bit confused as to which branch is also the current one here...

**Comment by maxentile** [comment]
Addressed -- now the required function is `benchmark.plotting.plot_scheme_comparison`
